main: de.craftlancer.imagemaps.ImageMaps
author: SydMontague
version: ${project.version}
name: ImageMaps
commands:
    imagemap:
        usage: "/imagemap <file> - then rightlick on a block"
        permission: imagemaps.use
permissions:
    imagemaps.use:
        default: op
    